### ISSUE TITLE
How to build from the source?

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/untitled-word-game#1]
How to build from the source ? 

The Makefile "dist: asm" section refers to a non-existant build/0boot build/ folder.

**Comment by peterferrie** [comment]
To build a disk image from the source, and mout that image, use "make all".
To build just a disk image from the source, use "make dist".
To build just the game code, use "make asm".

It's not a "dist: asm" section.  It's "dist:" calling the "asm" section.  asm creates the build directory, and then builds 0boot and the game itself.

**Comment by wyatt-wong** [comment]
> To build a disk image from the source, and mout that image, use "make all". To build just a disk image from the source, use "make dist". To build just the game code, use "make asm".
> 
> It's not a "dist: asm" section. It's "dist:" calling the "asm" section. asm creates the build directory, and then builds 0boot and the game itself.

Thanks.
